# This TOML is optimized for my blog at https://taintedcoders.com
tab_spaces = 2
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 80
max_width = 80
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "One"
newline_style = "Unix"
